(()=>{
const $=s=>document.querySelector(s);const audio=$('#audio'),play=$('#play'),title=$('#title'),artist=$('#artist'),cover=$('#cover'),coverFallback=$('#coverFallback'),queueList=$('#queueList'),artistList=$('#artistList'),seek=$('#seek'),elapsed=$('#elapsed'),duration=$('#duration'),volume=$('#volume');let tracks=[],index=0;
const fmt=s=>!Number.isFinite(s)?'0:00':`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
function artwork(src){cover.classList.remove('ready');coverFallback.classList.remove('hidden');if(!src){cover.removeAttribute('src');return}cover.onload=()=>{cover.classList.add('ready');coverFallback.classList.add('hidden')};cover.onerror=()=>{cover.classList.remove('ready');coverFallback.classList.remove('hidden')};cover.src=src}
function renderQueue(){queueList.innerHTML='';if(!tracks.length){queueList.innerHTML='<div class="empty">Dragon Radio is loading its first artist library. Check back shortly.</div>';return}tracks.forEach((t,i)=>{const b=document.createElement('button');b.className='queue-item'+(i===index?' current':'');b.innerHTML=`<span class="num">${String(i+1).padStart(2,'0')}</span><span><b>${escapeHtml(t.title||'Untitled')}</b><small>${escapeHtml(t.artist||'Dragon Radio')}</small></span><span>▶</span>`;b.onclick=()=>load(i,true);queueList.appendChild(b)})}
function renderArtists(){const map=new Map();tracks.forEach(t=>{const key=t.artist||'Dragon Radio';map.set(key,(map.get(key)||0)+1)});artistList.innerHTML='';if(!map.size){artistList.innerHTML='<div class="empty">Artist profiles will appear as music is added.</div>';return}for(const [name,count] of map){const d=document.createElement('div');d.className='artist-card';d.innerHTML=`<strong>${escapeHtml(name)}</strong><span>${count} track${count===1?'':'s'} in rotation</span>`;artistList.appendChild(d)}}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function load(i,autoplay=false){if(!tracks.length)return;index=(i+tracks.length)%tracks.length;const t=tracks[index];audio.src=t.src;title.textContent=t.title||'Untitled';artist.textContent=t.artist||'Dragon Radio';artwork(t.artwork);renderQueue();if(autoplay)audio.play().catch(()=>{})}
play.onclick=()=>{if(!tracks.length)return;audio.paused?audio.play().catch(()=>{}):audio.pause()};$('#prev').onclick=()=>load(index-1,true);$('#next').onclick=()=>load(index+1,true);audio.onplay=()=>play.textContent='❚❚';audio.onpause=()=>play.textContent='▶';audio.onended=()=>load(index+1,true);audio.ontimeupdate=()=>{elapsed.textContent=fmt(audio.currentTime);duration.textContent=fmt(audio.duration);seek.value=audio.duration?(audio.currentTime/audio.duration)*100:0};seek.oninput=()=>{if(audio.duration)audio.currentTime=(+seek.value/100)*audio.duration};volume.oninput=()=>audio.volume=+volume.value;audio.volume=+volume.value;
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
$('#shareBtn').onclick=async()=>{const data={title:'Dragon Radio',text:'Listen to Dragon Radio on DragonsRitual.',url:location.origin+'/'};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(data.url);$('#shareBtn').textContent='COPIED';setTimeout(()=>$('#shareBtn').textContent='SHARE',1300)}}catch{}};
fetch('/radio/library.json?'+Date.now(),{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('library');return r.json()}).then(data=>{tracks=(data.tracks||[]).filter(t=>t&&t.src);renderQueue();renderArtists();if(tracks.length)load(0);else{title.textContent='Dragon Radio';artist.textContent='First artist rotation coming online.';artwork('')}}).catch(()=>{title.textContent='Dragon Radio';artist.textContent='Station temporarily offline.';renderQueue();renderArtists()});
})();
