-- PASS 24 — DRAGON FIRST-PARTY ANALYTICS
-- Anonymous, cookieless session analytics for site launch/growth.
-- No IP address, fingerprint, password, form content or cross-site behavior is stored.

create table if not exists public.dr_analytics_sessions (
  session_id uuid primary key,
  started_at timestamptz not null default now(),
  landing_path text,
  referrer_domain text,
  channel text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  campaign_ref text,
  device_type text,
  browser_family text,
  viewport_bucket text,
  screen_width integer,
  screen_height integer,
  language text,
  host text,
  is_local boolean not null default false
);

create table if not exists public.dr_analytics_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.dr_analytics_sessions(session_id) on delete cascade,
  event_type text not null check (event_type in ('page_view','click','outbound_click','page_leave')),
  path text,
  target_path text,
  outbound_domain text,
  element_label text,
  page_title text,
  duration_ms bigint,
  host text,
  is_local boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists dr_analytics_sessions_started_idx on public.dr_analytics_sessions(started_at desc);
create index if not exists dr_analytics_sessions_campaign_idx on public.dr_analytics_sessions(utm_campaign, started_at desc);
create index if not exists dr_analytics_events_session_created_idx on public.dr_analytics_events(session_id, created_at);
create index if not exists dr_analytics_events_path_idx on public.dr_analytics_events(path, created_at desc);

alter table public.dr_analytics_sessions enable row level security;
alter table public.dr_analytics_events enable row level security;

-- Anyone visiting the public site may create an anonymous analytics session/event.
-- There is NO public SELECT policy.
drop policy if exists "public insert analytics sessions" on public.dr_analytics_sessions;
create policy "public insert analytics sessions" on public.dr_analytics_sessions
for insert to anon, authenticated
with check (true);

drop policy if exists "public insert analytics events" on public.dr_analytics_events;
create policy "public insert analytics events" on public.dr_analytics_events
for insert to anon, authenticated
with check (true);

-- Only director/founder/admin may read analytics.
drop policy if exists "director read analytics sessions" on public.dr_analytics_sessions;
create policy "director read analytics sessions" on public.dr_analytics_sessions
for select to authenticated
using (
  lower(coalesce(auth.jwt() ->> 'email','')) = 'dragonsritual@proton.me'
  or lower(coalesce(auth.jwt() -> 'user_metadata' ->> 'studio_role','')) in ('director','founder','admin')
);

drop policy if exists "director read analytics events" on public.dr_analytics_events;
create policy "director read analytics events" on public.dr_analytics_events
for select to authenticated
using (
  lower(coalesce(auth.jwt() ->> 'email','')) = 'dragonsritual@proton.me'
  or lower(coalesce(auth.jwt() -> 'user_metadata' ->> 'studio_role','')) in ('director','founder','admin')
);

-- Optional retention helper: call this manually/scheduled later if desired.
create or replace function public.dr_delete_old_analytics(days_to_keep integer default 365)
returns void
language sql
security definer
set search_path=public
as $$
  delete from public.dr_analytics_events where created_at < now() - make_interval(days => days_to_keep);
  delete from public.dr_analytics_sessions where started_at < now() - make_interval(days => days_to_keep);
$$;
