-- =========================================================
-- PASS 26 — PROFESSIONAL MEMBER ADMINISTRATION
-- Adds secure admin-only member status, badges, page permissions,
-- role assignment RPCs, notes and audit logging.
-- =========================================================

-- Extend member profiles with administrative fields.
alter table public.dr_member_profiles
  add column if not exists account_status text not null default 'active',
  add column if not exists director_note text,
  add column if not exists last_active_at timestamptz;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname='dr_member_profiles_account_status_check'
  ) then
    alter table public.dr_member_profiles
      add constraint dr_member_profiles_account_status_check
      check (account_status in ('active','paused','suspended','removed'));
  end if;
end $$;

-- Badge catalog for admin assignment.
create table if not exists public.dr_badge_definitions (
  id text primary key,
  name text not null,
  description text not null default '',
  category text not null default 'community',
  active boolean not null default true,
  sort_order integer not null default 100,
  created_at timestamptz not null default now()
);

create table if not exists public.dr_member_badges_admin (
  user_id uuid not null references auth.users(id) on delete cascade,
  badge_id text not null references public.dr_badge_definitions(id) on delete cascade,
  awarded_by uuid references auth.users(id) on delete set null,
  awarded_at timestamptz not null default now(),
  primary key(user_id,badge_id)
);

-- Per-member explicit route allowance.
create table if not exists public.dr_member_page_permissions (
  user_id uuid not null references auth.users(id) on delete cascade,
  path text not null,
  granted_by uuid references auth.users(id) on delete set null,
  granted_at timestamptz not null default now(),
  primary key(user_id,path)
);

-- Immutable-ish admin audit.
create table if not exists public.dr_member_admin_audit (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  target_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.dr_badge_definitions enable row level security;
alter table public.dr_member_badges_admin enable row level security;
alter table public.dr_member_page_permissions enable row level security;
alter table public.dr_member_admin_audit enable row level security;

grant select on public.dr_badge_definitions to authenticated;
grant select on public.dr_member_badges_admin to authenticated;
grant select on public.dr_member_page_permissions to authenticated;
grant select on public.dr_member_admin_audit to authenticated;

drop policy if exists "admins read badge definitions" on public.dr_badge_definitions;
create policy "admins read badge definitions"
on public.dr_badge_definitions for select to authenticated
using (public.is_admin());

drop policy if exists "admins read member badges" on public.dr_member_badges_admin;
create policy "admins read member badges"
on public.dr_member_badges_admin for select to authenticated
using (public.is_admin() or auth.uid()=user_id);

drop policy if exists "admins read page permissions" on public.dr_member_page_permissions;
create policy "admins read page permissions"
on public.dr_member_page_permissions for select to authenticated
using (public.is_admin() or auth.uid()=user_id);

drop policy if exists "admins read member audit" on public.dr_member_admin_audit;
create policy "admins read member audit"
on public.dr_member_admin_audit for select to authenticated
using (public.is_admin());

-- Admin can read all secure role rows (required for table).
drop policy if exists "members read own secure roles" on public.dr_member_roles;
create policy "members read own secure roles"
on public.dr_member_roles for select to authenticated
using (auth.uid()=user_id or public.is_admin());

-- Member profiles: admin can read all; member their own.
drop policy if exists "member read own profile" on public.dr_member_profiles;
create policy "member read own profile"
on public.dr_member_profiles for select to authenticated
using (auth.uid()=user_id or public.is_admin());

-- Seed badge catalog.
insert into public.dr_badge_definitions(id,name,description,category,sort_order) values
('first-step','First Step','Joined Dragon and established a member identity.','history',10),
('creator','Creator','Granted creator access inside Dragon.','studio',20),
('published','Published','Published original work through Dragon.','creation',30),
('broadcaster','Broadcaster','Participated in Dragon Radio or broadcast programming.','media',40),
('collaborator','Collaborator','Recognized for meaningful collaborative work.','community',50),
('founding-member','Founding Member','Part of the early DragonsRitual community.','history',60),
('featured','Featured','Selected for featured placement inside Dragon.','editorial',70),
('mentor','Mentor','Recognized for helping another creator grow.','community',80)
on conflict(id) do update
set name=excluded.name,
    description=excluded.description,
    category=excluded.category,
    sort_order=excluded.sort_order;

-- --------------------------------
-- Secure admin RPC helpers
-- --------------------------------

create or replace function public.dr_admin_set_member_status(
  target_user uuid,
  new_status text
)
returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  if not public.is_admin() then
    raise exception 'admin required';
  end if;

  if new_status not in ('active','paused','suspended','removed') then
    raise exception 'invalid status';
  end if;

  update public.dr_member_profiles
  set account_status=new_status,
      updated_at=now()
  where user_id=target_user;

  if new_status in ('suspended','removed') then
    delete from public.dr_member_roles
    where user_id=target_user
      and role <> 'member';
  end if;

  insert into public.dr_member_admin_audit(actor_user_id,target_user_id,action,metadata)
  values(auth.uid(),target_user,'status_changed',jsonb_build_object('status',new_status));
end;
$$;

create or replace function public.dr_admin_replace_member_roles(
  target_user uuid,
  new_roles text[]
)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare
  r text;
begin
  if not public.is_admin() then
    raise exception 'admin required';
  end if;

  -- Never allow this RPC to create admin/director privilege.
  if exists(
    select 1 from unnest(coalesce(new_roles,'{}'::text[])) x
    where x in ('admin','director','founder')
  ) then
    raise exception 'admin/director roles cannot be assigned here';
  end if;

  delete from public.dr_member_roles
  where user_id=target_user and role<>'member';

  insert into public.dr_member_roles(user_id,role,assigned_by)
  values(target_user,'member',auth.uid())
  on conflict do nothing;

  foreach r in array coalesce(new_roles,'{}'::text[]) loop
    if r in ('creator','writer','illustrator','radio','comics','streaming','3d','editor') then
      insert into public.dr_member_roles(user_id,role,assigned_by)
      values(target_user,r,auth.uid())
      on conflict do nothing;
    end if;
  end loop;

  -- Assigning any creator/workstation role automatically ensures creator.
  if exists(
    select 1 from unnest(coalesce(new_roles,'{}'::text[])) x
    where x in ('writer','illustrator','radio','comics','streaming','3d','editor')
  ) then
    insert into public.dr_member_roles(user_id,role,assigned_by)
    values(target_user,'creator',auth.uid())
    on conflict do nothing;
  end if;

  update public.dr_member_profiles
  set account_status='active',updated_at=now()
  where user_id=target_user;

  insert into public.dr_member_admin_audit(actor_user_id,target_user_id,action,metadata)
  values(auth.uid(),target_user,'roles_replaced',jsonb_build_object('roles',new_roles));
end;
$$;

create or replace function public.dr_admin_replace_member_badges(
  target_user uuid,
  new_badges text[]
)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare
  b text;
begin
  if not public.is_admin() then
    raise exception 'admin required';
  end if;

  delete from public.dr_member_badges_admin where user_id=target_user;

  foreach b in array coalesce(new_badges,'{}'::text[]) loop
    if exists(select 1 from public.dr_badge_definitions where id=b and active=true) then
      insert into public.dr_member_badges_admin(user_id,badge_id,awarded_by)
      values(target_user,b,auth.uid())
      on conflict do nothing;
    end if;
  end loop;

  insert into public.dr_member_admin_audit(actor_user_id,target_user_id,action,metadata)
  values(auth.uid(),target_user,'badges_replaced',jsonb_build_object('badges',new_badges));
end;
$$;

create or replace function public.dr_admin_replace_member_page_permissions(
  target_user uuid,
  new_paths text[]
)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare
  p text;
begin
  if not public.is_admin() then
    raise exception 'admin required';
  end if;

  delete from public.dr_member_page_permissions where user_id=target_user;

  foreach p in array coalesce(new_paths,'{}'::text[]) loop
    if left(p,1)='/' and length(p)<=240 then
      insert into public.dr_member_page_permissions(user_id,path,granted_by)
      values(target_user,p,auth.uid())
      on conflict do nothing;
    end if;
  end loop;

  insert into public.dr_member_admin_audit(actor_user_id,target_user_id,action,metadata)
  values(auth.uid(),target_user,'page_permissions_replaced',jsonb_build_object('paths',new_paths));
end;
$$;

create or replace function public.dr_admin_set_member_note(
  target_user uuid,
  new_note text
)
returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  if not public.is_admin() then
    raise exception 'admin required';
  end if;

  update public.dr_member_profiles
  set director_note=left(coalesce(new_note,''),5000),
      updated_at=now()
  where user_id=target_user;

  insert into public.dr_member_admin_audit(actor_user_id,target_user_id,action)
  values(auth.uid(),target_user,'director_note_updated');
end;
$$;

revoke all on function public.dr_admin_set_member_status(uuid,text) from public;
revoke all on function public.dr_admin_replace_member_roles(uuid,text[]) from public;
revoke all on function public.dr_admin_replace_member_badges(uuid,text[]) from public;
revoke all on function public.dr_admin_replace_member_page_permissions(uuid,text[]) from public;
revoke all on function public.dr_admin_set_member_note(uuid,text) from public;

grant execute on function public.dr_admin_set_member_status(uuid,text) to authenticated;
grant execute on function public.dr_admin_replace_member_roles(uuid,text[]) to authenticated;
grant execute on function public.dr_admin_replace_member_badges(uuid,text[]) to authenticated;
grant execute on function public.dr_admin_replace_member_page_permissions(uuid,text[]) to authenticated;
grant execute on function public.dr_admin_set_member_note(uuid,text) to authenticated;

-- Secure member-side helpers for page access checks.
create or replace function public.dr_my_page_permissions()
returns text[]
language sql
stable
security definer
set search_path=public
as $$
  select coalesce(array_agg(path order by path),'{}'::text[])
  from public.dr_member_page_permissions
  where user_id=auth.uid();
$$;

revoke all on function public.dr_my_page_permissions() from public;
grant execute on function public.dr_my_page_permissions() to authenticated;

-- Account-status helper.
create or replace function public.dr_my_account_status()
returns text
language sql
stable
security definer
set search_path=public
as $$
  select coalesce(
    (select account_status from public.dr_member_profiles where user_id=auth.uid()),
    'active'
  );
$$;

revoke all on function public.dr_my_account_status() from public;
grant execute on function public.dr_my_account_status() to authenticated;
