-- PASS 23: DRAGON MEMBER SYSTEM
-- Run this in Supabase SQL Editor BEFORE expecting member cards/trails to populate.

create table if not exists public.dr_member_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  handle text unique,
  bio text,
  member_type text default 'member',
  creator_type text,
  role text,
  studio_role text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.dr_member_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id uuid,
  event_type text not null check (event_type in ('session_start','page_view','click','page_leave')),
  path text,
  referrer_path text,
  target_path text,
  page_title text,
  element_label text,
  duration_ms bigint,
  created_at timestamptz not null default now()
);

create index if not exists dr_member_events_user_created_idx
  on public.dr_member_events(user_id, created_at desc);
create index if not exists dr_member_events_session_idx
  on public.dr_member_events(session_id);

alter table public.dr_member_profiles enable row level security;
alter table public.dr_member_events enable row level security;

-- A member may read/update only their own profile.
drop policy if exists "member read own profile" on public.dr_member_profiles;
create policy "member read own profile" on public.dr_member_profiles
for select using (
  auth.uid() = user_id
  or lower(coalesce(auth.jwt() ->> 'email','')) = 'dragonsritual@proton.me'
  or lower(coalesce(auth.jwt() -> 'user_metadata' ->> 'studio_role','')) in ('director','founder','admin')
);

drop policy if exists "member update own profile" on public.dr_member_profiles;
create policy "member update own profile" on public.dr_member_profiles
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "member insert own profile" on public.dr_member_profiles;
create policy "member insert own profile" on public.dr_member_profiles
for insert with check (auth.uid() = user_id);

-- Members can insert their own activity only.
drop policy if exists "member insert own events" on public.dr_member_events;
create policy "member insert own events" on public.dr_member_events
for insert with check (auth.uid() = user_id);

-- Activity is private to the director/admin account, not to other members.
drop policy if exists "director read member events" on public.dr_member_events;
create policy "director read member events" on public.dr_member_events
for select using (
  lower(coalesce(auth.jwt() ->> 'email','')) = 'dragonsritual@proton.me'
  or lower(coalesce(auth.jwt() -> 'user_metadata' ->> 'studio_role','')) in ('director','founder','admin')
);

-- Create a member profile automatically when an Auth user is created.
create or replace function public.dr_create_member_profile()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.dr_member_profiles(user_id,email,display_name,member_type,created_at,updated_at)
  values(
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(coalesce(new.email,''),'@',1)),
    case
      when lower(coalesce(new.raw_user_meta_data ->> 'studio_role','')) in ('director','founder','admin') then 'director'
      when new.raw_user_meta_data ? 'creator_type' or new.raw_user_meta_data ? 'creator_types' then 'creator'
      else 'member'
    end,
    now(),now()
  )
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_dr_member on auth.users;
create trigger on_auth_user_created_dr_member
after insert on auth.users
for each row execute procedure public.dr_create_member_profile();

-- Backfill existing accounts so current users get cards too.
insert into public.dr_member_profiles(user_id,email,display_name,member_type,created_at,updated_at)
select
  id,
  email,
  coalesce(raw_user_meta_data ->> 'display_name', split_part(coalesce(email,''),'@',1)),
  case
    when lower(coalesce(raw_user_meta_data ->> 'studio_role','')) in ('director','founder','admin') then 'director'
    when raw_user_meta_data ? 'creator_type' or raw_user_meta_data ? 'creator_types' then 'creator'
    else 'member'
  end,
  created_at,
  now()
from auth.users
on conflict (user_id) do nothing;
