-- DragonsRitual v0.7
-- Cross-device/account foundation.
-- Apply only after the v0.6 initial schema exists.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.device_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  device_class text not null check (device_class in ('mobile','tablet','desktop')),
  app_surface text not null check (
    app_surface in ('web','pwa','android','ios','desktop')
  ),
  last_page text,
  game_id uuid references public.games(id) on delete set null,
  session_id uuid references public.sessions(id) on delete set null,
  world_location_id uuid references public.world_locations(id) on delete set null,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.reward_definitions (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  title text not null,
  description text,
  reward_type text not null,
  surface_requirement text check (
    surface_requirement is null or
    surface_requirement in ('web','pwa','android','ios','desktop','mobile-any')
  ),
  active boolean not null default true,
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.reward_claims (
  id uuid primary key default gen_random_uuid(),
  reward_id uuid not null references public.reward_definitions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  claimed_at timestamptz not null default now(),
  claim_source text not null,
  verification_data jsonb not null default '{}'::jsonb,
  unique(reward_id, user_id)
);

create table if not exists public.live_channels (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  title text not null,
  channel_type text not null check (
    channel_type in ('market','world-event','score','stream','custom')
  ),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.live_channel_events (
  id bigint generated by default as identity primary key,
  channel_id uuid not null references public.live_channels(id) on delete cascade,
  payload jsonb not null,
  occurred_at timestamptz not null default now()
);

create index if not exists device_sessions_user_idx
  on public.device_sessions(user_id);

create index if not exists device_sessions_last_seen_idx
  on public.device_sessions(last_seen_at desc);

create index if not exists reward_claims_user_idx
  on public.reward_claims(user_id);

create index if not exists live_channel_events_channel_idx
  on public.live_channel_events(channel_id, occurred_at desc);

alter table public.profiles enable row level security;
alter table public.device_sessions enable row level security;
alter table public.reward_definitions enable row level security;
alter table public.reward_claims enable row level security;
alter table public.live_channels enable row level security;
alter table public.live_channel_events enable row level security;

-- Public catalog data only.
create policy "public read active rewards"
on public.reward_definitions
for select to anon, authenticated
using (active = true);

create policy "public read active live channels"
on public.live_channels
for select to anon, authenticated
using (active = true);

create policy "public read live channel events"
on public.live_channel_events
for select to anon, authenticated
using (true);

-- Authenticated users can see only their own profile/device/claims.
create policy "users read own profile"
on public.profiles
for select to authenticated
using (auth.uid() = id);

create policy "users update own profile"
on public.profiles
for update to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "users read own device sessions"
on public.device_sessions
for select to authenticated
using (auth.uid() = user_id);

create policy "users insert own device sessions"
on public.device_sessions
for insert to authenticated
with check (auth.uid() = user_id);

create policy "users update own device sessions"
on public.device_sessions
for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "users read own reward claims"
on public.reward_claims
for select to authenticated
using (auth.uid() = user_id);

-- Important:
-- No client-side INSERT policy is created for reward_claims.
-- Reward claims should later be issued by trusted server logic,
-- not by a browser saying "I am a phone."