-- DRAGON PASS 04 — platform/occupancy foundation. Run only after review in Supabase.
create table if not exists public.dragon_spaces (id uuid primary key default gen_random_uuid(),owner_user_id uuid not null references auth.users(id) on delete cascade,name text not null,slug text not null unique,space_type text not null check (space_type in ('creator','show','studio','shop','service','publication','community')),status text not null default 'draft' check (status in ('draft','active','paused','suspended')),plan text not null default 'free',description text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.dragon_campaigns (id uuid primary key default gen_random_uuid(),owner_user_id uuid not null references auth.users(id) on delete cascade,space_id uuid references public.dragon_spaces(id) on delete set null,title text not null,disclosure_label text not null default 'ADVERTISEMENT',status text not null default 'draft' check (status in ('draft','review','approved','active','paused','rejected','ended')),destination_url text,context_tags text[] not null default '{}',budget_credits integer not null default 0 check (budget_credits >= 0),starts_at timestamptz,ends_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.dragon_audit_events (id bigint generated always as identity primary key,actor_user_id uuid references auth.users(id) on delete set null,action text not null,object_type text not null,object_id text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
alter table public.dragon_spaces enable row level security; alter table public.dragon_campaigns enable row level security; alter table public.dragon_audit_events enable row level security;
create policy "spaces public active read" on public.dragon_spaces for select using (status='active' or auth.uid()=owner_user_id);
create policy "spaces owner insert" on public.dragon_spaces for insert with check (auth.uid()=owner_user_id);
create policy "spaces owner update" on public.dragon_spaces for update using (auth.uid()=owner_user_id) with check (auth.uid()=owner_user_id);
create policy "campaign owner read" on public.dragon_campaigns for select using (auth.uid()=owner_user_id);
create policy "campaign owner insert" on public.dragon_campaigns for insert with check (auth.uid()=owner_user_id);
create policy "campaign owner update" on public.dragon_campaigns for update using (auth.uid()=owner_user_id) with check (auth.uid()=owner_user_id);
-- Audit events intentionally have no browser policies. Trusted server/admin writes only.
